name: edureach
description: "An e-learning plartform"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

#============== PACKAGES ================#
dependencies:
  flutter:
    sdk: flutter

  #============== FIREBASE PACKAGES ================#
  firebase_core: ^3.12.1 # Firebase Core is required for Firebase services.
  firebase_auth: ^5.5.1 # Firebase Auth for user authentication.
  cloud_firestore: ^5.6.5 # Cloud Firestore is a NoSQL cloud database by Firebase.
  firebase_storage:
  flutter_cache_manager: ^3.3.0
  file_icon: ^1.0.0
  open_file: ^3.2.1 # for opening files:
  cached_network_image: # For image handling
  intl: ^0.18.0
  fl_chart: ^0.60.0

  #============== ICON PACKAGES ================#
  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #============== LOCAL ASSETS ================#
  assets:
    - assets/
